--Drop Scripts
DROP TABLE IF EXISTS SHIPPER;
DROP TABLE IF EXISTS CHANNEL;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS SHIPMENT;
DROP TABLE IF EXISTS ARRIVAL_STATUS;
DROP TABLE IF EXISTS SHIPPER_CHANNEL;
DROP TABLE IF EXISTS ARRIVAL;

--Create scripts
CREATE TABLE IF NOT EXISTS SHIPPER(ID UUID PRIMARY KEY, FIRST_NAME NVARCHAR2(100),LAST_NAME NVARCHAR2(100));
--CREATE TABLE IF NOT EXISTS CHANNEL(ID TINYINT PRIMARY KEY, CHANNEL_TYPE VARCHAR2(100));
CREATE TABLE IF NOT EXISTS LOCATION(ID UUID PRIMARY KEY, NAME NVARCHAR2(100));
CREATE TABLE IF NOT EXISTS SHIPMENT(ID UUID PRIMARY KEY, NAME NVARCHAR2(100));
CREATE TABLE IF NOT EXISTS ARRIVAL_STATUS(ID TINYINT PRIMARY KEY, NAME VARCHAR2(100));

CREATE TABLE IF NOT EXISTS SHIPPER_CHANNEL(SHIPPER_ID UUID, CHANNEL_TYPE VARCHAR2(20), ADDRESS VARCHAR2(100), 
	FOREIGN KEY(SHIPPER_ID) REFERENCES SHIPPER(ID));
CREATE TABLE IF NOT EXISTS ARRIVAL(SHIPMENT_ID UUID, DESTINATION_ID UUID,  EXPECTED_TIME SMALLDATETIME, FOREIGN KEY(SHIPMENT_ID) REFERENCES SHIPMENT(ID),
	FOREIGN KEY(DESTINATION_ID) REFERENCES LOCATION(ID), UNIQUE KEY UK_SHIP_DEST(SHIPMENT_ID,DESTINATION_ID), UNIQUE KEY UK_SHIP_SEQ(SHIPMENT_ID, EXPECTED_TIME));